export const WorkExperience = [
  {
    title: "Senior Software Engineer",
    company: "Kyosk Digital Services",
    location: "Nairobi, Kenya",
    dates: "February 2023 - Present",
    stack: [
      "Angular",
      "Nx",
      "GraphQL",
      "Rxjs",
      "Angular Material",
      "SCSS",
      "Jest",
      "Docker",
      "Kubernetes",
    ],
    responsibilities: [
      "Spearheaded the development of dynamic user interfaces using Angular and Angular Material, enhancing user engagement and interaction.",
      "Pioneered the implementation of micro frontends with Nx architecture, ensuring scalable and modular application components.",
      "Seamlessly integrated APIs and GraphQL queries, significantly boosting application functionality and user satisfaction.",
      "Engineered shared libraries and reusable components, streamlining development processes and enhancing team productivity.",
      "Provided mentorship on advanced micro frontend development practices, elevating the team's technical expertise and project quality.",
      "Optimized application performance with responsive, fast-loading designs, ensuring compatibility across all devices and browsers.",
      "Achieved remarkable code reliability with up to 80% code coverage through meticulous unit testing using Jest.",
      "Revolutionized application performance by implementing lazy loading, slashing load times by 50%.",
      "Championed best practices in front-end development, leading to improved application stability and user retention.",
    ],
  },
  {
    title: "Senior Software Engineer",
    company: "SKillcat",
    location: "Hanover Hermann Park, US",
    dates: "July 2021 - April 2023",
    stack: ["ReactJS", "Redux", "Ionic", "Tailwind", "Jest"],
    responsibilities: [
      "Designed and implemented cutting-edge hybrid mobile applications with Angular and Ionic, enhancing cross-platform functionality and user reach.",
      "Developed dynamic, responsive dashboards using ReactJS, Redux, and Tailwind CSS, delivering real-time data visualization and improved user experience.",
      "Ensured exceptional code quality through rigorous unit testing with Jest, leading to robust and reliable applications.",
      "Seamlessly integrated RESTful APIs, facilitating smooth and efficient frontend-backend communication and data exchange.",
      "Collaborated closely with UI/UX designers, creating visually appealing and intuitive user interfaces for mobile and web platforms.",
      "Boosted application performance by 20% through careful code optimization, enhancing overall user satisfaction.",
      "Conducted thorough code reviews, maintaining high code quality standards and fostering a culture of continuous improvement.",
    ],
  },
  {
    title: "Senior Software Engineer",
    company: "Konza Silicon",
    location: "Nairobi, Kenya",
    dates: "June 2019 - July 2021",
    stack: [
      "Angular 2+",
      "Angular Material",
      "SCSS",
      "pdfMake",
      "Leaflet.js",
      "Ngrx/Store",
      "Docker",
      "Kubernetes",
    ],
    responsibilities: [
      "Led a team of developers, fostering a collaborative and innovative work environment, and driving high team performance.",
      "Chaired sprint meetings, ensuring clear task allocation and timely completion.",
      "Ensured seamless frontend-backend integration, maintaining consistency and optimal functionality across applications.",
      "Directed front-end architecture design discussions, delivering scalable and maintainable solutions for complex projects.",
      "Developed dynamic dashboard applications using Angular, TypeScript, and SCSS, enhancing user experience and data accessibility.",
      "Collaborated closely with the UI/UX team to accurately implement intricate product designs, ensuring visual and functional excellence.",
      "Engineered a robust authentication module with JWT architecture, bolstering application security and user authentication processes.",
      "Reduced build times significantly by reusing components and minimizing redundant code, streamlining the development process.",
      "Enhanced application performance by implementing lazy loading techniques, reducing load times by 50%, and improving user retention.",
      "Created interactive data visualizations with D3.js and Chart.js, enabling users to easily interpret and engage with complex datasets.",
      "Implemented advanced geospatial visualizations using Leaflet and Mapbox GL JS, providing interactive mapping features for property information management.",
    ],
  },
  {
    title: "Software Engineer",
    company: "Endarasha Meadow Fresh Dairy",
    location: "Nyeri, Kenya",
    dates: "May 2018 - July 2019",
    stack: ["ReactJS", "Redux", "Tailwind CSS", "Docker", "Kubernetes"],
    responsibilities: [
      "Spearheaded the development of intuitive dashboard web applications using ReactJS, Redux, and Tailwind CSS, enhancing data visibility and user experience.",
      "Implemented robust state management with Redux, ensuring consistent and responsive UI/UX design across all platforms.",
      "Engineered backend solutions using Node.js and Express.js, delivering high-performance and scalable applications.",
      "Designed and built RESTful APIs, optimizing system performance and enabling seamless integration with various services.",
      "Managed comprehensive database integration and optimization with MongoDB, ensuring efficient data handling and retrieval.",
      "Ensured rigorous data integrity and security measures across the system, safeguarding sensitive dairy production information.",
      "Developed interactive data visualizations with Chart.js, providing clear and actionable insights into dairy production statistics.",
      "Fostered a collaborative development environment, working closely with cross-functional teams to deliver high-quality software solutions.",
    ],
  },
];
